apiVersion: v1
kind: Pod
metadata:
  name: docker-image-build
spec:
  containers:
  - name: movie-rating-docker-helm-build
    image: roeeyakir/movie-rating:0.1
    imagePullPolicy: Always
    securityContext:
      privileged: true

