apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rate
  labels:
    app: movie-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-rate
  template:
    metadata:
      labels:
        app: movie-rate
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: yakirlevi11/movie-rate-repo:{{ .Chart.Version }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.mysql.host }}
            - name: DB_PORT
              value: "{{ .Values.mysql.port }}"
            - name: DB_NAME
              value: {{ .Values.mysql.database }}
            - name: DB_USERNAME
              value: {{ .Values.mysql.username }}
            - name: DB_PASSWORD
              value: {{ .Values.mysql.password }}
