# Chart.yaml

apiVersion: v2
appVersion: "0.0.1" 

# ...

# values.yaml

image:
  repository: nginx
  tag: "0.0.1" 

# or parameterize
# tag: {{ .Chart.AppVersion }}

# ...

# templates/deployment.yaml

spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

# ...
