# Define your custom configuration options here, such as:
image:
  repository: roeedot/movie-rate-repo
  tag: "{{ .Chart.Version }}"
service:
  type: LoadBalancer
  port: 5000
  nodePort: null
mysql:
  enabled: true
  host: localhost
  port: "3306"
  database: recommended_films
  username: root
  password: a1a1a1
